### ISSUE TITLE
Remove A-Painter from main project

### ISSUE THREAD

**Issue by tbalouet** [tbalouet/aframe-slideshow#10]
A-Painter shouldn't be part of the main slideshow presentation repo, but should be included in the future for people willing to paint in their presentations.

Therefore we should remove it from the main project. That would also increase readability of the project itself

**Comment by Utopiah** [comment]
Since there is no version of apainter as a component it would mean, if one wants to draw on top of slides, to making the component "droppable" in apainter as-is (checking in particular camera issues).

**Comment by tbalouet** [comment]
Yes, I'll look into making an apainter-brush component which is independent from the apainter project, but that is outside of this project, more like a possible add-on

**Comment by Utopiah** [comment]
That's heavy but if you manage that will be HUGELY appreciated by the community as this has been requested numerous time.

**Comment by Utopiah** [comment]
closed?
