### ISSUE TITLE
Better way to list and include slides

### ISSUE THREAD

**Issue by Utopiah** [tbalouet/aframe-slideshow#2]
As of now the slides are hard links, might be better to have a more dynamic way to link them e.g. passing by URL

- the path (absolute or relative),
- number of slides and
- type of slides (image vs video)

and eventually generate those options by provider only the path (but would require server side processing).

**Comment by tbalouet** [comment]
Those changes were added in the latest commit (https://github.com/tbalouet/aframe-slideshow/commit/b29ca4c4bdc6823544ac856b2d990757d34e0814). The 'aframe-slideshow' has now the following properties
```
{
  transitionHeight  : {type: 'number', default: '2'},  
  folder            : {type: 'string', default: 'public/assets/slides/'},  
  nbslides          : {type: 'number', default: '0'},  
  stepTransition    : {type: 'number', default: '0.01'},
  startpos          : {type: 'vec3',   default: undefined},
  distBetweenSlides : {type: 'number', default: '5'},
  nbColumns         : {type: 'number', default: '5'},
  slideYPos         : {type: 'number', default: '1.6'}
}
```
